// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udbwynamyknfloazdjlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkYnd5bmFteWtuZmxvYXpkamxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MjI2ODMsImV4cCI6MjA1NTk5ODY4M30.unjBCIU7Sqzq8fiwfT2PL65oxSN7VzFMYaqcM-68sSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);